/*////////////////////////ESTRUCTURAS DE CONTROL, REPETITVAS, FUNCIONES///////////////////////////////*/
/*ESTRUCTURAS DE CONTROL CONDICIONAL: nos permite decidir que se va a ejecutar, se establecen condiciones o decisiones, if y else
-If hace referencia a una condicion simple, si pasa esto hace eesto
     If (condicion){BLOQUE DE INSTRUCCIONES}
PUEDE haber una condicion o mas de una separadas por operadores logicos && u ||
     if (condicion && condicion) || {BLOQUE DE INSTRUCCIONES}     
If else 
     if (condicion) {} else {} la 
La simplificacion es el operador ternario
     (cond) ? 'aqui' : (otro);*/

if (nota>10) {console.log} 